# Generated by Django 3.2 on 2025-11-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mes', '0001_initial'),
        ('Anio', '0001_initial'),
        ('Valor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarifa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Refsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usuarios', models.CharField(max_length=200)),
                ('variacion_bimestral', models.CharField(max_length=200)),
                ('variacion_intermensual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Consumo_energetico.tipotarifa')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='Cammesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.CharField(max_length=200)),
                ('variacion_interanual', models.CharField(max_length=200)),
                ('variacion_intermensual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Consumo_energetico.tipotarifa')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
    ]
