# Generated by Django 3.2 on 2025-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='total',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventaarticulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventaparticipacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
