# Generated by Django 6.0.2 on 2026-04-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anio', '0001_initial'),
        ('Mes', '0001_initial'),
        ('Valor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccesoInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=200)),
                ('variacion_interanual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
                ('tipo_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AccesoInternet.tipoacceso')),
            ],
        ),
    ]
