# Generated by Django 3.2 on 2025-09-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Valor', '0001_initial'),
        ('Anio', '0001_initial'),
        ('Mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SectorConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_empresas', models.CharField(max_length=200)),
                ('total_puesto_trabajo', models.CharField(max_length=200)),
                ('salario_promedio', models.CharField(max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_interanual', models.CharField(max_length=200)),
                ('variacion_intermensual', models.CharField(max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tipo_dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Sector_construccion.tipodato')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
    ]
