# Generated by Django 6.0.2 on 2026-03-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anio', '0001_initial'),
        ('Mes', '0001_initial'),
        ('Valor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ganado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoTotalProteina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='StockPecuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BigIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
                ('tipo_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Pecuario.tipoganado')),
            ],
        ),
        migrations.CreateModel(
            name='FaenaPecuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabezas', models.BigIntegerField()),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
                ('tipo_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Pecuario.tipoganado')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoCapita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
                ('tipo_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Pecuario.tipoganado')),
            ],
        ),
    ]
