# Generated by Django 6.0.2 on 2026-04-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anio', '0001_initial'),
        ('Mes', '0001_initial'),
        ('Pecuario', '0001_initial'),
        ('Valor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocapita',
            name='consumo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faenapecuario',
            name='cabezas',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockpecuario',
            name='stock',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ProdDestIndustria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produccion', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tipo_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Pecuario.tipoganado')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
    ]
