# Generated by Django 3.2 on 2025-10-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Descripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
