# Generated by Django 3.2 on 2025-10-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoresprivado',
            name='diferencia_interanual',
            field=models.CharField(default=0.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicadoresprivado',
            name='diferencia_intermensual',
            field=models.CharField(default=0.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicadoresprivado',
            name='variacion_interanual',
            field=models.CharField(default=0.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicadoresprivado',
            name='variacion_intermensual',
            field=models.CharField(default=0.0, max_length=200),
            preserve_default=False,
        ),
    ]
