# Generated by Django 4.2.27 on 2026-01-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Valor', '0001_initial'),
        ('Mes', '0001_initial'),
        ('Anio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionCampaniaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_sembrada', models.CharField(max_length=200)),
                ('superficie_cosechada', models.CharField(max_length=200)),
                ('produccion', models.CharField(max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('Campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Productivo.campaniacultivo')),
                ('TipoCultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Productivo.tipocultivo')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionProdFormosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion', models.CharField(max_length=200)),
                ('Campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Productivo.campaniacultivo')),
                ('TipoCultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Productivo.tipocultivo')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresPrecioCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_nacional', models.CharField(max_length=200)),
                ('precio_internacional', models.CharField(max_length=200)),
                ('variacion_mensual', models.CharField(max_length=200)),
                ('variacion_fob', models.CharField(max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('TipoCultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Productivo.tipocultivo')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
            ],
        ),
    ]
